### ISSUE TITLE
Possible values for `speed`

### ISSUE THREAD

**Issue by bradfordcp** [Property404/lionchief-controller#1]
What are the possible values for setting the speed (or at least a min/max)?

**Comment by Property404** [comment]
Minimum is 0x00(ie off). Not sure the maximum, but I think it at least goes up to 0x0b

**Comment by bradfordcp** [comment]
I've tried a range of values with what appears to be certain ones overflowing back to 0 (0x80 for example will cause the locomotive to stop). Hoping to get this narrowed down a bit more with some other testing. Have you looked into the command to change directions?

**Comment by Property404** [comment]
It may also just be looking at the least-significant nibble.  

I haven't, but if I find time to do it I'll let you know. Should be simple, since it probably has no parameters, or just a boolean on/off  

If you want to try yourself, here are some instructions:
Have Android (I'm using 10.x)
Enable developer options
Enable USB debugging
Enable Bluetooth debugging to file(not sure if this is actually necessary)
Plug device into a host via USB (I'm using Fedora 33)
Allow USB debugging for that host
Start the ADB server (make sure you can connect to your Android device)  
Open Wireshark on the host
On the opening screen, there should be an option for debugging Bluetooth on the Android device, click it
Type "btatt" into the display filter to filter out all the crap
Open LionChief app and connect to your train
(Optional) Clear packets from wire shark
Put train into reverse
Look at the packet coming from localhost to remote. It will probably be the third-to-last and second-to-last bytes that will be part of the command. The last byte is the checksum
Add new method to the LionChief class

**Comment by Property404** [comment]
Forward is `0x46 0x01`
Reverse is `0x46 0x02`

Max speed I can get with the app is `0x1f`
